### ISSUE TITLE
lint & fix commands detect no violations

### ISSUE THREAD

**Issue by srjonemed** [sqlfluff/sqlfluff#1086]
-- If this is a parsing or linting issue, please include a minimal SQL example which reproduces the issue, along with the `sqlfluff parse` output, `sqlfluff lint` output and `sqlfluff fix` output when relevant. Finally, please add any labels that are related to the issue before submitting so that it can be addressed easily! --

## Expected Behaviour
When I run ```sqlfluff lint --verbose models/mymodel.sql``` it always returns 0 violations and Pass status while i know there are violations in the sql

## Observed Behaviour
```
$ sqlfluff lint --verbose models/testsql.sql
==== sqlfluff ====
sqlfluff:           0.5.3 python:             3.7.7
dialect:        snowflake verbosity:              1
templater:            dbt dbt:              =0.19.1
rules:      L001, L002, L003, L004, L005,
            L006, L007, L008, L009, L010,
            L011, L012, L013, L018, L019,
            L022, L023, L024, L025, L029,
            L030, L036, L037, L038, L039,
       L041, L044, L045, L046, L047, L048
==== readout ====
=== [ path: models/testsql.sql ] ===
=== [dbt templater] Compiling dbt project...
== [models/testsql.sql] PASS
==== summary ====
violations:        0 status:         PASS 
```
## Steps to Reproduce
Check previous section

## Version
Include the output of `sqlfluff --version` along with your Python version
```sqlfluff, version 0.5.3```

## Configuration
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
#templater = jinja
templater = dbt
rules = None
exclude_rules = L031 
recurse = 0
output_line_length = 80
runaway_limit = 10
ignore_templated_areas = True
ignore = parsing,templating
# Comma separated list of file extensions to lint.
​
# NB: This config will only apply in the root folder.
sql_file_exts = .sql,.dml,.ddl
​
[sqlfluff:indentation]
indented_joins = False
template_blocks_indent = True
​
[sqlfluff:templater]
unwrap_wrapped_queries = True
​
[sqlfluff:templater:jinja]
apply_dbt_builtins = True
​
[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable) %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}
​
# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 4
max_line_length = 120
indent_unit = space
comma_style = trailing
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all
​
# Some rules have their own specific config.
[sqlfluff:rules:L003]
lint_templated_tokens = True
​
[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = consistent
​
[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = consistent
​
[sqlfluff:rules:L016]
ignore_comment_lines = False
​
[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = aliases
​
[sqlfluff:rules:L030]  # Function names
capitalisation_policy = consistent
​
[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid
​
[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = consistent
​
[sqlfluff:rules:L042]
# By default, allow subqueries in from clauses, but not join clauses.
forbid_subquery_in = join
​
[sqlfluff:rules:L047]  # Consistent syntax to count all rows
prefer_count_1 = False
​
[sqlfluff:rules:L039]
ignore = False

```

**Comment by srjonemed** [comment]
More information for triaging -
* This is a dbt project, and in model sql file, I've purposefully added semi-colon to test violation
```
$ cat models/testsql.sql
WITH dim_company AS (
    SELECT
        company,
        company_code,
        hq
    FROM {{ source('companies', 'dim_company') }}
    )
SELECT * FROM dim_company
;
```

* dbt_project.yml 
```
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'common_ref_models'
version: '1.0.0'
config-version: 2
​
# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake'
​
# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
​
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
​
vars:
    ANALYTICS_STAGING: "de_staging"
    ANALYTICS_RAW_STORE: "de_raw_store"
    ANALYTICS_SCHEMA: "de_schema"
​
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
​
# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    materialized: view

```
