### ISSUE TITLE
DbtProjectError exception when using using the new dbt "query-comment" configuration

### ISSUE THREAD

**Issue by alepuccetti** [sqlfluff/sqlfluff#1225]
Error when using using the new `query-comment` configuration in the `dbt_project.yml`, example:
```yml
query-comment:
  append: false
  job-label: true   # BigQuery only
```

## Expected Behaviour
Regular execution

## Observed Behaviour
When running `sqlfluff lint`, `sqlfluff fix`, or `sqlfluff parse` the execution exit with this error:
```bash
dbt.exceptions.DbtProjectError: Runtime Error
  at path ['query-comment']: {'append': False, 'job-label': True} is not valid under any of the given schemas
```

## Steps to Reproduce

1. Add the following in your `dbt_project.yml`
```yml
query-comment:
  append: false
  job-label: true   # BigQuery only
```
2. Execute any of `sqlfluff lint`, `sqlfluff fix`, or `sqlfluff parse.

## Version
Include the output of `sqlfluff --version` along with your Python version:
```bash
sqlfluff, version 0.6.1
Python 3.9.6
```

## Configuration
```
[sqlfluff]
templater = dbt
dialect = bigquery
exclude_rules = L031
```
