### ISSUE TITLE
Test suite doesn't handle some multiples in YAML files

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#1273]
I noticed this in https://github.com/sqlfluff/sqlfluff/pull/1269#discussion_r687560810 but also stumbled across it again in a more recent PR.

To repeat edit the `test/fixtures/parser/bigquery/select_mixture_of_array_literals.sql` file and change this line:

```sql
    ['a'] AS strcol1,
```

to this:

```sql
    ['a', 'b'] AS strcol1,
```

Still valid SQL right?

We also change the equivalent YAML file from this:

```yml
            array_literal:
              start_square_bracket: '['
              expression:
                literal: "'a'"
              end_square_bracket: ']'
```

to this:

```yml
            array_literal:
              start_square_bracket: '['
              expression:
                literal: "'a'"
              comma: ','
              expression:
                literal: "'b'"
              end_square_bracket: ']'
```

We then run the test suite:

```
tox -e cov-init,py38,cov-report,linting
```

The SQL test completes fine (it's valid SQL after all):

```
test/dialects/dialects_test.py::test__dialect__base_file_parse[bigquery-select_mixture_of_array_literals.sql] ✓                                                                            35% ███▌      
 ```

However the YAML check later fails:

```py
――――――――――――――――――――――――――――――――――――――― test__dialect__base_parse_struct[bigquery-select_mixture_of_array_literals.sql-True-select_mixture_of_array_literals.yml] ――――――――――――――――――――――――――――――――――――――――

dialect = 'bigquery', sqlfile = 'select_mixture_of_array_literals.sql', code_only = True, yamlfile = 'select_mixture_of_array_literals.yml', yaml_loader = <function load_yaml at 0x7feb35a62940>

    @pytest.mark.parametrize("dialect,sqlfile,code_only,yamlfile", parse_structure_examples)
    def test__dialect__base_parse_struct(
        dialect, sqlfile, code_only, yamlfile, yaml_loader
    ):
        """For given test examples, check parsed structure against yaml."""
        # Load the right dialect
        config = FluffConfig(overrides=dict(dialect=dialect))
        # Load the SQL
        raw = load_file(dialect, sqlfile)
        # Lex and parse the file
        tokens, _ = Lexer(config=config).lex(raw)
        parsed = Parser(config=config).parse(tokens)
        # Load the YAML
        res = yaml_loader(make_dialect_path(dialect, yamlfile))
        if parsed:
>           assert parsed.to_tuple(code_only=code_only, show_raw=True) == res

...
E                        (('expression',
E                          (('array_literal',
E                            (('start_square_bracket',
E                              '['),
E                             ('expression',
E                              (('literal',
E             -                  "'b'"),)),
E             ?                    ^
E             +                  "'a'"),)),
E             ?                    ^
E                             ('comma',
E                              ','),
E             +               ('expression',
E             +                (('literal',
E             +                  "'b'"),)),
E                             ('end_square_bracket',
E                              ']'))),)),

...

 test/dialects/dialects_test.py::test__dialect__base_parse_struct[bigquery-select_mixture_of_array_literals.sql-True-select_mixture_of_array_literals.yml] ⨯                                59% █████▉    
 ```

As you can see one side of the comparisons seems to think this is `['b']` instead of `['a', 'b']` - it's like using multiple values replaces the previous values with the latest.

Using the `parse` command:

```
sqlfluff parse --dialect=bigquery test/fixtures/parser/bigquery/select_mixture_of_array_literals.sql -f yaml
```

This does handle this fine. So it's just a test suite issue.

Trying it with a `-` (I [never really understood this in YAML](https://www.reddit.com/r/ansible/comments/5jhff3/when_to_use_dash_in_yaml/) to be honest!)

```yml
            array_literal:
              - start_square_bracket: '['
              - expression:
                literal: "'a'"
              - comma: ','
              - expression:
                literal: "'b'"
              - end_square_bracket: ']'
```

Gives a slightly different error with a clue what's wrong:

```py
    def process_struct(obj):
        """Process a nested dict or dict-like into a check tuple."""
        if isinstance(obj, dict):
            return tuple((k, process_struct(obj[k])) for k in obj)
        elif isinstance(obj, list):
            # We'll assume that it's a list of dicts
            if isinstance(obj[0], dict):
                buff = [process_struct(elem) for elem in obj]
                if any(len(elem) > 1 for elem in buff):
>                   raise ValueError(f"Not sure how to deal with multi key dict: {buff!r}")
E                   ValueError: Not sure how to deal with multi key dict: [(('start_square_bracket', '['),), (('expression', None), ('literal', "'a'")), (('comma', ','),), (('expression', None), ('literal', "'b'")), (('end_square_bracket', ']'),)]

test/conftest.py:28: ValueError
```

So it's not a big issue, in that the code still works with multiple elements in real life. But it does limit our test suite ability, and can be frustrating when getting weird random errors when you're trying to do the right thing and add good test cases.

This looks like a hard core Python and SQLFluff so not sure I have the skills to help with this one (I only dabble in Python), so not sure if one of the maintainers can comment on it?
