### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by andrew-farries** [sqlfluff/sqlfluff#1874]
I'd love to be able to use SQLFluff for workloads running on Kubernetes. There are a few unofficial SQLFluff images [floating around on Dockerhub](https://hub.docker.com/search?q=sqlfluff&type=image) but nothing official.

Are there plans to maintain an official docker image somewhere? I'd be happy to help with the effort if so.

**Comment by WittierDinosaur** [comment]
I'm up for it if there's an appetite. As someone who isn't that up with K8s, and so-so at Docker, can you explain a) the benefit, and b) how big an undertaking it is?

**Comment by andrew-farries** [comment]
The benefit would be twofold IMO:

**Comment by andrew-farries** [comment]
The benefit would be twofold IMO:

* Easier install for people working locally who might not want to install python + dependencies. In that case SQLFluff could be run as a one-shot command, something like:

  ```bash
  docker run -it --rm -v $PWD/sql:/sql sqlfluff lint /sql --dialect postgres
  ```

  to lint the contents of a `./sql` directory without having to install anything.

* Ability to run SQLFluff as a container inside a Kubernetes pod. I have a Kubernetes application in which pods are started periodically to clone some SQL migration scripts from a Github repository and run some checks against them. I'd like for SQLFluff linting to be one of those checks, and having a SQLFluff docker image is a prerequisite for that (K8S will only run containers, not any other kind of process).

The cost to this project would be building and uploading a docker image to Dockerhub for every new release. The `Dockerfile` itself would be easy enough - something like:

```Dockerfile
FROM python:3.10

RUN pip install sqlfluff==0.8.1

USER 5000

ENTRYPOINT ["sqlfluff"]

CMD ["--help"]
```

Building and pushing this image would be done automatically by a Github Actions workflow.

**Comment by barrywhart** [comment]
@andrew-farries: Do you have interest in creating a PR for this?

**Comment by jpy-git** [comment]
I'd probably do the Dockerfile like:
```Dockerfile
FROM python:3.10-slim-bullseye

WORKDIR /sqlfluff

COPY src ./src
COPY setup.py .
COPY README.md .

RUN pip install --upgrade pip
RUN python -m venv .venv && . .venv/bin/activate
RUN pip install .

USER 5000

ENTRYPOINT ["sqlfluff"]

CMD ["--help"]
```
to just build the docker image from the master branch so we don't worry about updating the version reference in the Dockerfile.
Runs same way with `docker run -it --rm -v $PWD:/sqlfluff sqlfluff lint test <file>`

Then when we do a release you could have a Github Actions workflow setup like described here https://github.com/docker/build-push-action, but tweaked to build/push on release:
```yml
name: Publish SQFluff Docker Hub Version

on:
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: <USER>/sqlfluff:latest
```

Only other thing that would need to be done is for someone to setup a Docker Hub User/Token for SQLFLUFF (maybe @alanmcruickshank?) and put those in Github Secrets for the repo for Github Actions to use.
