### ISSUE TITLE
Add 'reflow' capability for configurable, black-like deterministic formatting

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#2436]
# Feature
Same functionality as black, but totally configurable. The 'reflow' command would produce a deterministic output for the same 'code_only' input, regardless of the non-code elements (whitespace, capitalisation, indentation).

## Benefits:
- Fully user configurable code style
- Deterministic output for queries with the same choice and order of code segments
- No need to maintain and create rules for formatting-only concerns, which is hard currently as we have to detect bad SQL, which has infinite possibilities. By letting the user decide what good SQL is, we only have to define how the SQL is rendered.
- The implementation suggested is purely additive in relation to the parse tree, mitigating issues where formatting rules can interfere with each other.

## Illustrative example
The user has a sql file with the following:
```
select a,b, 
c FROM schema.table TBL
```

The user has configured the following:
```
base:
  case: lower # render all base segments (BaseSegment) and children in lowercase
select_clause_elements:
  indent_from_parent: 1 # indents all of `select_clause_elements_segment` by one unit from parent segment (this grouping segment doesn't exist yet)
select_clause_element:
  pre_newline: true # adds a newline before `select_clause_element`
from_clause:
  pre_newline: true # adds a newline before `from_clause`
```
And so the output is:
```
select
    a,
    b,
    c
from schema.table tbl
```

## How
We're already embedding Indent and Dedent into the dialects, this feature builds upon that to add all configuration and functionality to render valid SQL from code-only elements.
1. We parse the SQL as usual
2. We remove all non-code segments from the parse tree (output here is what our dialect test fixture ymls look like).
3. Using this parse tree, we render the 'reflowed' SQL.

## We've talked for a while about the idea of separating rules by what they do. It seems we can clearly draw a line between:
1. Rules which care about query structure (choice and ordering of code segments)
2. Rules which just care about appearance (non-code segments, strictly whitespace, capitalisation and indentation).

This feature focuses strictly on the latter and would not add, remove or modify code segments beyond their capitalisation.

## Implementation suggestions
- Embed the rendering logic into the dialect grammars/segments for maximum maintainability and ease of contribution. This is deliberately moving away from the approach in [L003](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/rules/L003.py) which is very difficult to maintain due to its aim of handling all indentation across every grammar and segment.
- Unless a segment/grammar has unique rendering logic, it can inherit the logic and behaviour from its parent. For instance, we only need to define 'case' and `pre_newline` config at the top level segment.
- Configuration precedence and inheritance:
  - 1. User-specified configuration
  - 2. 'Theme'-specified configuration (we could have a library of SQL styles which could be used as a base)
  - 3. Segment specified configuration
  - 4. Next closest parent segment configuration (e.g. `SchemaReferenceSegment` would use `ObjectReferenceSegment`'s configuration if it did not have its own).
  - Acceptance criteria for a V1 could be that we're just able to render valid SQL from code-only segments. We can add configurable style after that.
- Not all formatting rules are as simple as 'always add newlines before select elements'. But, we could make segment-specific configurations. For example there could feasibly be a config for `select_clause_element: pre_newline_when_multiple`.

My current availability combined with the fact that there are many much better developers than me around here means I would really love to see someone/others take this on, I'm not precious about any of the above ideas!
