### ISSUE TITLE
Parser: Differentiate between references between target and source tables

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#3046]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

It'd be useful to distinguish in the parse tree between tables which are the subject of a query, and ones that are being used to change the subject table. Eg:

```
CREATE OR REPLACE <table> AS ...

target_table_identifier:
    table_identifier:
        identifier: <table>
```

vs

```
SELECT * FROM table ...

queried_table:
    table_identifier:
       identifier: <table>
```

This would make using SQLFluff for interpretation much easier

### Use case

-

### Dialect

-

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
