### ISSUE TITLE
check-column-name-contract is unavailable via pre-commit

### ISSUE THREAD

**Issue by daniel-inventa** [sqlfluff/sqlfluff#3244]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Ran `pre-commit run` with the following in `.pre-commit-config.yaml`:
```
repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v1.0.0
  hooks:
  - id: check-column-name-contract
    args: [--pattern, "(is|has|do)_.*", --dtype, boolean]
- repo: https://github.com/psf/black
```

### Expected Behaviour

the `check-column-name-contract` check is run

### Observed Behaviour

it throws the following error:
```
[ERROR] `check-column-name-contract` is not present in repository https://github.com/offbi/pre-commit-dbt.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.
```

### How to reproduce

Run `pre-commit run` with the following in `.pre-commit-config.yaml`:
```
repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v1.0.0
  hooks:
  - id: check-column-name-contract
    args: [--pattern, "(is|has|do)_.*", --dtype, boolean]
- repo: https://github.com/psf/black
```

### Dialect

snowflake

### Version

`sqlfluff, version 0.13.0`
`pre-commit 2.18.1`

### Configuration

```
# .sqlfluff
[sqlfluff]
dialect = snowflake
templater = dbt
exclude_rules = L011, L031, L032, L034

[sqlfluff:templater:jinja]
apply_dbt_builtins = True
load_macros_from_path = ./dbt_packages/dbt_utils/macros

# Allow mocking dbt_utils and other packages through
# python files placed in this dir
library_path = sqlfluff_libs

[sqlfluff:templater:dbt]
project_dir = ./
profile = default

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable, default='') %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}

# Mock variables that are used in dbt
[sqlfluff:templater:dbt:context]
target = ci

[sqlfluff:rules:L014]
capitalisation_policy = lower

```

```
# .sqlfluffignore
target/
dbt_modules/
dbt_packages/
macros/
logs/

.dbtenv/
.gitignore

```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
