### ISSUE TITLE
SOQL: Recognize nested objects

### ISSUE THREAD

**Issue by greg-finley** [sqlfluff/sqlfluff#3322]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

In SOQL, many objects, like `Account` and `Contact`, have a relationship under the hood. Instead of writing a `JOIN`, you reference columns from the other object like so:

```soql
SELECT Account.Name FROM Contact
```

### Use case

It should be parseable

### Dialect

soql

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
The example SQL you provided parses successfully already in both `soql` and `ansi` dialects. Can you clarify what you mean by "It should be parseable"?

**Comment by greg-finley** [comment]
I get this, with no sqlfluff config.

```
gregoryfinley@Gregorys-MacBook-Pro git-repos % echo "SELECT Account.Name FROM Contact" > test.sql
gregoryfinley@Gregorys-MacBook-Pro git-repos % sqlfluff lint test.sql --dialect ansi             
== [test.sql] FAIL                                                                                                                                       
L:   1 | P:   8 | L026 | Reference 'Account.Name' refers to table/view not found
                       | in the FROM clause or found in ancestor statement.
All Finished 📜 🎉!
gregoryfinley@Gregorys-MacBook-Pro git-repos % 
```

It should not raise this warning, because it's ok that `Account` is not in this query.

**Comment by greg-finley** [comment]
Though it will generate a parse tree. I'm confused ...
```
# YML test files are auto-generated from SQL files and should not be edited by
# hand. To help enforce this, the "hash" field in the file must match a hash
# computed by SQLFluff when running the tests. Please run
# `python test/generate_parse_fixture_yml.py`  to generate them after adding or
# altering SQL files.
_hash: a4667f2c8fa6b42fe78bcabf1b39505d18fc6a7a89d261aba8476d7441f7cd81
file:
  statement:
    select_statement:
      select_clause:
        keyword: SELECT
        select_clause_element:
          column_reference:
          - identifier: Account
          - dot: .
          - identifier: Name
      from_clause:
        keyword: FROM
        from_expression:
          from_expression_element:
            table_expression:
              table_reference:
                identifier: Contact
```
