### ISSUE TITLE
Redshift parse exception in `CREATE OR REPLACE FUNCTION` statement

### ISSUE THREAD

**Issue by menzenski** [sqlfluff/sqlfluff#3457]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

This statement throws a parsing error:

```sql
CREATE OR REPLACE FUNCTION public.iif(
    condition BOOLEAN
    , true_result ANYELEMENT
    , false_result ANYELEMENT) RETURNS ANYELEMENT
STABLE
AS
$$
    if condition:
        return true_result
    return false_result
$$
LANGUAGE plpythonu;
```

### Expected Behaviour

I expected this SQL to be parsed without error.

### Observed Behaviour

This is valid Redshift SQL but it does not parse in SQLFluff.

### How to reproduce

The SQL above is the entire contents of a file `sql_files/functions/helpers/iif.sql` in my repository. The exact command I ran was `sqlfluff lint --nocolor -v sql_files/functions/helpers/iif.sql`.

If I run with `-vvvvv` the output is this: [error.log](https://github.com/sqlfluff/sqlfluff/files/8911994/error.log)

### Dialect

Redshift

### Version

```
$ sqlfluff --version
sqlfluff, version 0.13.2
```

```
$ python -V
Python 3.9.11
```

### Configuration

`.sqlfluff`

```toml
[sqlfluff]
dialect = redshift
nocolor = False
templater = placeholder

[sqlfluff:indentation]
indented_ctes = True
indented_joins = True
indented_using_on = True

[sqlfluff:rules]
comma_style = leading
indent_unit = space
max_line_length = 120
tab_space_size = 4

[sqlfluff:rules:L010]
capitalisation_policy = upper

[sqlfluff:rules:L011]
aliasing = explicit

[sqlfluff:rules:L012]
aliasing = explicit

[sqlfluff:rules:L014]
extended_capitalisation_policy = lower
unquoted_identifiers_policy = all

[sqlfluff:rules:L016]
ignore_comment_clauses = True
ignore_comment_lines = True

[sqlfluff:rules:L026]
force_enable = False

[sqlfluff:rules:L030]
extended_capitalisation_policy = lower

[sqlfluff:rules:L040]
capitalisation_policy = upper

[sqlfluff:rules:L051]
fully_qualify_join_types = both

[sqlfluff:rules:L052]
multiline_newline = False
require_final_semicolon = True

[sqlfluff:rules:L059]
prefer_quoted_identifiers = False

[sqlfluff:rules:L063]
extended_capitalisation_policy = upper

[sqlfluff:templater:placeholder]
param_style = numeric_dollar
version = '0.0.0'
# This is NOT the pw but it is a string of the same length and alphanum character set
aws_glue_pw = 'M9a16TZerGcBuGEHRoM9zJkFURfEkx7kCC9QxmNlkT5bsCmVkW659eKdE1PYvX8'
1 = TRUE
2 = two
3 = three
```

`.sqlfluffignore`

```
/templates/
/changelogs/db/00_setup/100_databases.sql
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
