### ISSUE TITLE
L027 does not work with UNNEST WITH OFFSET

### ISSUE THREAD

**Issue by DamianS21** [sqlfluff/sqlfluff#4274]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I have found that sqlfluff raises an issue with L027 when using variable from `USING WITH OFFSET`
Message:
```
L:  43 | P:  44 | L027 | Unqualified reference 'column_index_raw' found in select
                       | with more than one referenced table/view.
```

the query:
```
SELECT
column_index_raw
FROM table1 as aux
INNER JOIN cte1 AS aux_y
        ON aux.variable = aux_y.variable,
        UNNEST(["A", "B", "C", "D", "E", "F", "G", "H", "J", "K"]) AS letters
        WITH
        OFFSET
        AS column_index_raw
```
same happens with
```
SELECT
column_index_raw
FROM table1 as aux
INNER JOIN cte1 AS aux_y
        ON aux.variable = aux_y.variable
        INNER JOIN
        UNNEST(["A", "B", "C", "D", "E", "F", "G", "H", "J", "K"]) AS letters
        WITH
        OFFSET
        AS column_index_raw
```
also same happens without using an alias, so:
```
SELECT
OFFSET
FROM table1 as aux
INNER JOIN cte1 AS aux_y
        ON aux.variable = aux_y.variable
        INNER JOIN
        UNNEST(["A", "B", "C", "D", "E", "F", "G", "H", "J", "K"]) AS letters
        WITH
        OFFSET
```

### Expected Behaviour

`SELECT column_index_raw ...` returns the offset value and sqlfluff understands that OFFSET created alias doesn't have a reference

### Observed Behaviour

Sqlfluff lint raises an issue when trying to use the offseted variable
```
Unqualified reference 'column_index_raw' found in select
                       | with more than one referenced table/view.
```

### How to reproduce

1. Create a dbt image sql file with usage of `INNER JOIN UNNEST <variable> WITH OFFSET AS <alias>`
2. Use the aliast in SELECT statement
3. run `sqlfluff lint -d bigquery -t dbt models/file.sql`

### Dialect

bigquery

### Version

1.4.2

### Configuration

```
target/
packages/
macros/
dbt_packages/
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by DamianS21** [comment]
Issue is still happening.

**Comment by PaddyAlton** [comment]
I think I'm also seeing this issue (or a related one - it's `RF01` that trips for me): 

```sql
SELECT
    some_table.id,
    element_name,  -- lack of reference does not cause a problem
    element_rank, -- noqa: RF01
FROM
    {{ ref('some_table') }}  -- we're using dbt
CROSS JOIN
    UNNEST(some_array) AS element_name
    WITH OFFSET AS element_rank
```

This is using Google SQL / BigQuery / dbt.

Versions are `v3.3.1` for `sqlfluff` and `sqlfluff-dbt-templater`. Full config as follows:

```toml
[tool.sqlfluff.core]
templater = "dbt"
dialect = "bigquery"
exclude_rules = "LT08, L034"

[tool.sqlfluff.rules.aliasing.table]
table = "explicit"
[tool.sqlfluff.rules.aliasing.column]
column = "explicit"

[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "upper"
[tool.sqlfluff.rules.capitalisation.identifiers]
capitalisation_policy = "lower"
[tool.sqlfluff.rules.capitalisation.functions]
extended_capitalisation_policy = "upper"
[tool.sqlfluff.rules.capitalisation.literals]
capitalisation_policy = "lower"
[tool.sqlfluff.rules.capitalisation.types]
extended_capitalisation_policy = "upper"

[tool.sqlfluff.rules.convention.select_trailing_comma]
select_clause_trailing_comma = "require"
```
