### ISSUE TITLE
dry-run for dbt-compiled sql models

### ISSUE THREAD

**Issue by Almaz-Murzabekov** [sqlfluff/sqlfluff#4298]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

It would be nice to have a dry-run check for the SQL validity. Often, dbt compile command produces invalid SQL files (like missing column names, etc). 

### Use case

I want to run the following two commands to make sure that we didn't broke any dbt model
> if ! $files; then sqlfluff lint $files; fi
> if ! $files; then dry-run lint $files; fi

Right, now, we run a separate `dry-run.sh` script for this case, and the script runs for following code
sql: "explain &file_content" which gives an physical plan of execution, of error message in case of invalid sql.

I'm thinking is it possible to incorporate this approach to sqlfluff tool

### Dialect

dbt-spark

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
This is a *very* interesting idea, which I don't think has come up before. I much prefer `validate` to `dry-run`, and we'd also need a way of managing credentials to a database.

@Almaz-Murzabekov - how do you manage credentials in your scripted setup?

**Comment by barrywhart** [comment]
Is "validate" basically equivalent to "parse all the files, reporting any parse errors"?

About credentials, that's not unique to this issue, right? With the dbt templater, SQLFluff (well, actually dbt itself) *always* connects to the database.

**Comment by Almaz-Murzabekov** [comment]
> This is a _very_ interesting idea, which I don't think has come up before. I much prefer `validate` to `dry-run`, and we'd also need a way of managing credentials to a database.
> 
> @Almaz-Murzabekov - how do you manage credentials in your scripted setup?

Actually, credentials are set in `.sqlfluff` file, like this
```
[sqlfluff:templater:dbt]
project_dir = analytics_dbt_databricks/
profile = analytics_dbt
target = gitlab-ci
```
and the creds for gitlab-ci database is set in dbt_profiles.yml file, something like this

```
analytics_dbt:
  send_anonymous_usage_stats: False
  target: dev
  outputs:
    dev:
    // dev creds
    prod:
    // prod creds
    gitlab-ci:
      type: databricks
      schema: utility
      host: $host
      token: "{{ env_var('DBT_GITLAB_CI_DATABRICKS_TOKEN') }}"
      http_path: "$path
      threads: 1
```
