### ISSUE TITLE
BigQuery UNPIVOT is unparseable if single column unpivot used with row value alias

### ISSUE THREAD

**Issue by imrehg** [sqlfluff/sqlfluff#4486]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Writing an `UNPIVOT` query with row value alias, and it results in unparseable error, even though it works just fine within BigQuery.

### Expected Behaviour

Using an unpivot in the shape of:
```
...
UNPIVOT
  values_column
  FOR name_column
  IN (colum_1 AS value 1, column_2 AS...)
```
to work.

### Observed Behaviour

Seems like as long as either
a) do not use value aliases, things work
```
...
UNPIVOT
  values_column
  FOR name_column
  IN (colum_1, column_2, ...)
```
or;

b) when using column groups, things work, e.g. the example from this other issue: https://github.com/sqlfluff/sqlfluff/issues/2920 in the form of

```
UNPIVOT
  (values_column1, values_column2)
  FOR name_column
  IN ((colum_1, column_2) AS 1, ...)
```
does work. But a single column (not group) doesn't.

### How to reproduce

This example is based on the [BigQuery UNPIVOT docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#unpivot_operator):

1) open https://online.sqlfluff.com/ and select `bigquery` dialect

2) a row value alias [example](https://online.sqlfluff.com/fluffed?sql=H4sIAJ2fCWQC_3WQywqDMBBF94H8w-BKwUWNEddSlIbapPioa2mzK9Tn_zePSgPirC4nF3JmOtZcYJg-r_UpIavBxwjU1HmZnxub9XjX_i09XbDdJfy_JZHmY-QgEhtEHEQTg2IH2RK1oOVMcMjK8kAgG4ZDgzTdGZx2AmQvQDaBACOM3C9nte78a45rPy1ywqioxG27FUYtv7OHaHxThUJUWxEYB380R4lC5aADUcGsG6tAdaCB-vQLzJl3on4BAAA%3D&dialect=bigquery)

```sql
WITH produce AS (
    SELECT
        "Kale" AS product,
        51 AS q1,
        23 AS q2,
        45 AS q3,
        3 AS q4
    UNION ALL
    SELECT
        "Apple" AS product,
        77 AS q1,
        0 AS q2,
        25 AS q3,
        2 AS q4
)

SELECT
    sales,
    quarter
FROM produce
UNPIVOT(sales FOR quarter IN (q1 AS 1, q2 AS 2, q3 AS 3, q4 AS 4))
```
doesn't pass.

3) a non-value aliased [query](https://online.sqlfluff.com/fluffed?sql=H4sIAByfCWQC_3WQsQqDMBRF90D-4eEUoUONirMUpaE2KRrbWVq3QjXq_zcxlQaCb3qcd-Ge5MHkGQb1eS3PHvIGCEagpymq4iTtbia4dO8-MAGbnQ__WxoZPkYOovGKqIOSdEWxg2wosaDlTHDIq2pHIB-GXYMs8wyOngD1BegmEGKEkVs56edOv-S4dGruFUZlLa7bX2HU8hu7C0nWKJSi3oLAOBAtY-pNn24Iwy95pIXVaAEAAA%3D%3D&dialect=bigquery)

```sql
WITH produce AS (
    SELECT
        "Kale" AS product,
        51 AS q1,
        23 AS q2,
        45 AS q3,
        3 AS q4
    UNION ALL
    SELECT
        "Apple" AS product,
        77 AS q1,
        0 AS q2,
        25 AS q3,
        2 AS q4
)

SELECT
    sales,
    quarter
FROM produce
UNPIVOT(sales FOR quarter IN (q1, q2, q3, q4))
```
does pass.

Both queries work in the BigQuery console.

The multi-column example from the above linked Issue is also parseable.

### Dialect

bigquery

### Version

* sqlfluff, version 1.4.5
* Python 3.9.12
* dbt core 1.3.1 / dbt-bigquery 1.3.0

### Configuration

```toml
# pyproject.toml content
[tool.sqlfluff.core]
templater = "dbt"
dialect = "bigquery"
sql_file_exts = ".sql,.sql.j2"
exclude_rules = "L032"

[tool.sqlfluff.rules]
tab_space_size = 2
max_line_length = 120
indent_unit = "space"

[tool.sqlfluff.rules.L010]
# Keywords
capitalisation_policy = "upper"

[tool.sqlfluff.rules.L014]
# Unquoted identifiers
extended_capitalisation_policy = "lower"

[tool.sqlfluff.rules.L030]
# Function names
extended_capitalisation_policy = "upper"

[tool.sqlfluff.rules.L040]
# Null & Boolean Literals
capitalisation_policy = "upper"

[tool.sqlfluff.rules.L063]
# Data Types
extended_capitalisation_policy = "upper"

[tool.sqlfluff.templater]
unwrap_wrapped_queries = true
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
