### ISSUE TITLE
snowflake using SAMPLE with a $variable is unparsable 

### ISSUE THREAD

**Issue by jamesowers-roo** [sqlfluff/sqlfluff#4643]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

# System info
```shell
% sqlfluff --version
sqlfluff, version 2.0.2
% uname -a
Darwin N40Y0N4XRJ 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64
```

# Minimal working example
The following is valid snowflake SQL:

```sql
SET sample_size = 10;
WITH dummy_data AS (
    SELECT SEQ4() AS row_number
    FROM TABLE(GENERATOR(rowcount => 1000)) 
    ORDER BY row_number
)
SELECT * FROM dummy_data SAMPLE ($sample_size ROWS);
```

However, trying to parse it with sqlfluff I get the following parse error:
```shell
% sqlfluff parse --dialect snowflake sql/dummy.sql
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        set_statement:
[L:  1, P:  1]      |            keyword:                                          'SET'
[L:  1, P:  4]      |            whitespace:                                       ' '
[L:  1, P:  5]      |            variable:                                         'sample_size'
[L:  1, P: 16]      |            whitespace:                                       ' '
[L:  1, P: 17]      |            comparison_operator:
[L:  1, P: 17]      |                raw_comparison_operator:                      '='
[L:  1, P: 18]      |            whitespace:                                       ' '
[L:  1, P: 19]      |            expression:
[L:  1, P: 19]      |                numeric_literal:                              '10'
[L:  1, P: 21]      |    statement_terminator:                                     ';'
[L:  1, P: 22]      |    newline:                                                  '\n'
[L:  2, P:  1]      |    statement:
[L:  2, P:  1]      |        with_compound_statement:
[L:  2, P:  1]      |            keyword:                                          'WITH'
[L:  2, P:  5]      |            whitespace:                                       ' '
[L:  2, P:  6]      |            common_table_expression:
[L:  2, P:  6]      |                naked_identifier:                             'dummy_data'
[L:  2, P: 16]      |                whitespace:                                   ' '
[L:  2, P: 17]      |                keyword:                                      'AS'
[L:  2, P: 19]      |                whitespace:                                   ' '
[L:  2, P: 20]      |                bracketed:
[L:  2, P: 20]      |                    start_bracket:                            '('
[L:  2, P: 21]      |                    [META] indent:
[L:  2, P: 21]      |                    newline:                                  '\n'
[L:  3, P:  1]      |                    whitespace:                               '    '
[L:  3, P:  5]      |                    select_statement:
[L:  3, P:  5]      |                        select_clause:
[L:  3, P:  5]      |                            keyword:                          'SELECT'
[L:  3, P: 11]      |                            [META] indent:
[L:  3, P: 11]      |                            whitespace:                       ' '
[L:  3, P: 12]      |                            select_clause_element:
[L:  3, P: 12]      |                                function:
[L:  3, P: 12]      |                                    function_name:
[L:  3, P: 12]      |                                        function_name_identifier:  'SEQ4'
[L:  3, P: 16]      |                                    bracketed:
[L:  3, P: 16]      |                                        start_bracket:        '('
[L:  3, P: 17]      |                                        end_bracket:          ')'
[L:  3, P: 18]      |                                whitespace:                   ' '
[L:  3, P: 19]      |                                alias_expression:
[L:  3, P: 19]      |                                    keyword:                  'AS'
[L:  3, P: 21]      |                                    whitespace:               ' '
[L:  3, P: 22]      |                                    naked_identifier:         'row_number'
[L:  3, P: 32]      |                        newline:                              '\n'
[L:  4, P:  1]      |                        whitespace:                           '    '
[L:  4, P:  5]      |                        [META] dedent:
[L:  4, P:  5]      |                        from_clause:
[L:  4, P:  5]      |                            keyword:                          'FROM'
[L:  4, P:  9]      |                            whitespace:                       ' '
[L:  4, P: 10]      |                            from_expression:
[L:  4, P: 10]      |                                [META] indent:
[L:  4, P: 10]      |                                from_expression_element:
[L:  4, P: 10]      |                                    table_expression:
[L:  4, P: 10]      |                                        function:
[L:  4, P: 10]      |                                            function_name:
[L:  4, P: 10]      |                                                function_name_identifier:  'TABLE'
[L:  4, P: 15]      |                                            bracketed:
[L:  4, P: 15]      |                                                start_bracket:  '('
[L:  4, P: 16]      |                                                [META] indent:
[L:  4, P: 16]      |                                                expression:
[L:  4, P: 16]      |                                                    function:
[L:  4, P: 16]      |                                                        function_name:
[L:  4, P: 16]      |                                                            function_name_identifier:  'GENERATOR'
[L:  4, P: 25]      |                                                        bracketed:
[L:  4, P: 25]      |                                                            start_bracket:  '('
[L:  4, P: 26]      |                                                            [META] indent:
[L:  4, P: 26]      |                                                            snowflake_keyword_expression:
[L:  4, P: 26]      |                                                                parameter:  'rowcount'
[L:  4, P: 34]      |                                                                whitespace:  ' '
[L:  4, P: 35]      |                                                                parameter_assigner:  '=>'
[L:  4, P: 37]      |                                                                whitespace:  ' '
[L:  4, P: 38]      |                                                                numeric_literal:  '1000'
[L:  4, P: 42]      |                                                            [META] dedent:
[L:  4, P: 42]      |                                                            end_bracket:  ')'
[L:  4, P: 43]      |                                                [META] dedent:
[L:  4, P: 43]      |                                                end_bracket:  ')'
[L:  4, P: 44]      |                                [META] dedent:
[L:  4, P: 44]      |                        whitespace:                           ' '
[L:  4, P: 45]      |                        newline:                              '\n'
[L:  5, P:  1]      |                        whitespace:                           '    '
[L:  5, P:  5]      |                        orderby_clause:
[L:  5, P:  5]      |                            keyword:                          'ORDER'
[L:  5, P: 10]      |                            whitespace:                       ' '
[L:  5, P: 11]      |                            keyword:                          'BY'
[L:  5, P: 13]      |                            [META] indent:
[L:  5, P: 13]      |                            whitespace:                       ' '
[L:  5, P: 14]      |                            column_reference:
[L:  5, P: 14]      |                                naked_identifier:             'row_number'
[L:  5, P: 24]      |                            [META] dedent:
[L:  5, P: 24]      |                    newline:                                  '\n'
[L:  6, P:  1]      |                    [META] dedent:
[L:  6, P:  1]      |                    end_bracket:                              ')'
[L:  6, P:  2]      |            newline:                                          '\n'
[L:  7, P:  1]      |            select_statement:
[L:  7, P:  1]      |                select_clause:
[L:  7, P:  1]      |                    keyword:                                  'SELECT'
[L:  7, P:  7]      |                    [META] indent:
[L:  7, P:  7]      |                    whitespace:                               ' '
[L:  7, P:  8]      |                    select_clause_element:
[L:  7, P:  8]      |                        wildcard_expression:
[L:  7, P:  8]      |                            wildcard_identifier:
[L:  7, P:  8]      |                                star:                         '*'
[L:  7, P:  9]      |                whitespace:                                   ' '
[L:  7, P: 10]      |                [META] dedent:
[L:  7, P: 10]      |                from_clause:
[L:  7, P: 10]      |                    keyword:                                  'FROM'
[L:  7, P: 14]      |                    whitespace:                               ' '
[L:  7, P: 15]      |                    from_expression:
[L:  7, P: 15]      |                        [META] indent:
[L:  7, P: 15]      |                        from_expression_element:
[L:  7, P: 15]      |                            table_expression:
[L:  7, P: 15]      |                                table_reference:
[L:  7, P: 15]      |                                    naked_identifier:         'dummy_data'
[L:  7, P: 25]      |                        [META] dedent:
[L:  7, P: 25]      |                    whitespace:                               ' '
[L:  7, P: 26]      |                    unparsable:                               !! Expected: 'Nothing...'
[L:  7, P: 26]      |                        raw:                                  'SAMPLE'
[L:  7, P: 32]      |                        whitespace:                           ' '
[L:  7, P: 33]      |                        bracketed:
[L:  7, P: 33]      |                            start_bracket:                    '('
[L:  7, P: 34]      |                            raw:                              '$sample_size'
[L:  7, P: 46]      |                            whitespace:                       ' '
[L:  7, P: 47]      |                            raw:                              'ROWS'
[L:  7, P: 51]      |                            end_bracket:                      ')'
[L:  7, P: 52]      |    statement_terminator:                                     ';'
[L:  7, P: 53]      |    newline:                                                  '\n'
[L:  8, P:  1]      |    [META] end_of_file:

==== parsing violations ====
L:   7 | P:  26 |  PRS | Line 7, Position 26: Found unparsable section: 'SAMPLE
                       | ($sample_size ROWS)'
WARNING: Parsing errors found and dialect is set to 'snowflake'. Have you configured your dialect correctly?
```

### Expected Behaviour

The issue is in the use of `$sample_size` - if this is changed to a number, it will parse.

I would expect sqlfluff to be able to handle this.

### Observed Behaviour

see "What Happened"

### How to reproduce

see "What Happened"

### Dialect

snowflake

### Version

2.0.2

### Configuration

```toml
[tool.sqlfluff]
max_line_length = 88

# Some rules can be configured directly from the config common to other rules.
[tool.sqlfluff.rules]
allow_scalar = true
single_table_references = "consistent"
unquoted_identifiers_policy = "all"

[tool.sqlfluff.indentation]
# See https://docs.sqlfluff.com/en/stable/layout.html#configuring-indent-locations
indent_unit = "space"
tab_space_size = 4
indented_joins = false
indented_ctes = false
indented_using_on = true
indented_on_contents = true
allow_implicit_indents = false
template_blocks_indent = true
# This is a comma seperated list of elements to skip
# indentation edits to.
skip_indentation_in = "script_content"
# If comments are found at the end of long lines, we default to moving
# them to the line _before_ their current location as the convention is
# that a comment precedes the line it describes. However if you prefer
# comments moved _after_, this configuration setting can be set to "after".
trailing_comments = "before"

# Some rules have their own specific config.
# https://docs.sqlfluff.com/en/stable/rules.html
[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "upper"
# unquoted identifiers i.e. column names
extended_capitalisation_policy = "lower"

[tool.sqlfluff.rules."aliasing.table"]
aliasing = "explicit"

[tool.sqlfluff.rules."aliasing.column"]  # Column aliasing
aliasing = "explicit"

[tool.sqlfluff.rules."aliasing.expression"]  # Column expressions
allow_scalar = false

[tool.sqlfluff.rules.capitalisation.identifiers]  # Unquoted identifiers
extended_capitalisation_policy = "lower"

[tool.sqlfluff.rules.layout.long_lines]
# Ignore length added by inline comments
ignore_comment_clauses = true
# But if a line is just a comment, then do insist on that line length being considered
ignore_comment_lines = false

[tool.sqlfluff.rules.references.keywords]  # Keyword identifiers
unquoted_identifiers_policy = "aliases"

[tool.sqlfluff.rules.capitalisation.functions]  # Function names
extended_capitalisation_policy = "upper"

[tool.sqlfluff.rules.convention.select_trailing_comma]
select_clause_trailing_comma = "forbid"

[tool.sqlfluff.rules.capitalisation.literals]  # Null & Boolean Literals
capitalisation_policy = "upper"

[tool.sqlfluff.rules.structure.subquery]
# Do not allow subqueries in either FROM nor JOIN clauses.
forbid_subquery_in = "both"

[tool.sqlfluff.rules.convention.count_rows]  # Consistent syntax to count all rows
prefer_count_1 = false
prefer_count_0 = false

[tool.sqlfluff.rules.references.quoting] # Unnecessary quoted identifier
ignore_words = "date"

[tool.sqlfluff.rules.capitalisation.types] # Consistent datatypes
extended_capitalisation_policy = "upper"
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
