### ISSUE TITLE
Incorrect Parse Tree for Lateral View in sparksql Dialect

### ISSUE THREAD

**Issue by reata** [sqlfluff/sqlfluff#4978]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

For the following sql used in https://github.com/sqlfluff/sqlfluff/blob/2.1.2/test/fixtures/dialects/sparksql/select_from_lateral_view.sql:
```sql
SELECT
    p.id,
    exploded_people.name,
    exploded_people.age,
    exploded_people.state
FROM person AS p
    LATERAL VIEW INLINE(array_of_structs) exploded_people AS name, age, state;
```

The generated yml is https://github.com/sqlfluff/sqlfluff/blob/2.1.2/test/fixtures/dialects/sparksql/select_from_lateral_view.yml
```yml
- statement:
    select_statement:
      select_clause:
      - keyword: SELECT
      - select_clause_element:
          column_reference:
          - naked_identifier: p
          - dot: .
          - naked_identifier: id
      - comma: ','
      - select_clause_element:
          column_reference:
          - naked_identifier: exploded_people
          - dot: .
          - naked_identifier: name
      - comma: ','
      - select_clause_element:
          column_reference:
          - naked_identifier: exploded_people
          - dot: .
          - naked_identifier: age
      - comma: ','
      - select_clause_element:
          column_reference:
          - naked_identifier: exploded_people
          - dot: .
          - naked_identifier: state
      from_clause:
      - keyword: FROM
      - from_expression:
          from_expression_element:
            table_expression:
              table_reference:
                naked_identifier: person
            alias_expression:
              keyword: AS
              naked_identifier: p
            lateral_view_clause:
            - keyword: LATERAL
            - keyword: VIEW
            - function:
                function_name:
                  function_name_identifier: INLINE
                bracketed:
                  start_bracket: (
                  expression:
                    column_reference:
                      naked_identifier: array_of_structs
                  end_bracket: )
            - naked_identifier: exploded_people
            - alias_expression:
                keyword: AS
                naked_identifier: name
      - comma: ','
      - from_expression:
          from_expression_element:
            table_expression:
              table_reference:
                naked_identifier: age
      - comma: ','
      - from_expression:
          from_expression_element:
            table_expression:
              table_reference:
                naked_identifier: state
```

The parse tree is wrong in that only name is parsed as column alias, while age and state are incorrectly parsed as from_expression.

### Expected Behaviour

Based on SparkSQL manual: https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-lateral-view.html
`name, age, state` are column alias and should all fall under lateral_view_clause. 

### Observed Behaviour

This bug was introduced by [#4731 ](https://github.com/sqlfluff/sqlfluff/pull/4731/files#diff-3eda0f12c73b596b60f05524af281a9de6954a544984d186fe5297355d2c81dfL1710), where the intention was to allow keyword AS as optional, which brought this side effect at the same time.

The interesting thing is that, based on [SparkSQL documentation](https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-lateral-view.html), AS is mandatory. However, if we check the parser implementation ([SqlBaseParser.g4](https://github.com/apache/spark/blob/v3.4.1/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBaseParser.g4#L690) as generated by ANTLR4 ), we'll find AS in lateral view is indeed optional.

So we need to continue support AS in lateral veiw as optional, while tweaking the parse tree to be correct.

### How to reproduce

```shell
pytest -s test/dialects/dialects_test.py -k sparksql-select_from_lateral_view.sql
```

since the current yml is incorrect, the test shall pass.

### Dialect

sparksql

### Version

`>=2.0.4`

### Configuration

not needed

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
