### ISSUE TITLE
dbt is unable to pick up the secret-key to service account for db connection and perform linting

### ISSUE THREAD

**Issue by LaniusSenatorShrike** [sqlfluff/sqlfluff#5097]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

In the last two weeks, I've been struggling to add SQLFLUFF linter to CI pipeline with Jenkins. In my local, I pass dbt the secret-key to the service account with the profiles.yml file as in below: (look at `JSON_KEYFILE)`
``` 
default:
  target: nonprod
  outputs:
    nonprod:
      type: bigquery
      method: service-account-json
      project: "emt-nonprod-8avl"
      dataset: "DATASET_PLACEHOLDER"
      threads: 10
      timeout_seconds: 3000
      location: EU
      priority: interactive
      retries: 1
      keyfile_json: "{{ fromjson(env_var('JSON_KEYFILE'))}}"
``` 
having this, then I run pre-commit as in below
``` 
repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.2.0
    hooks:
      - id: sqlfluff-lint
        verbose: true
        name: sqlfluff-lint
        additional_dependencies: [
          'dbt-bigquery==1.5.1',
          'sqlfluff-templater-dbt==2.2.0'
        ]
``` 
but when it comes to do it on CI pipeline it is not successful. The steps I've taken that initially I have passed the secret-key to Jenkins files as an environment variable `(JSON_KEYFILE = credentials('ecg-emt-json-keyfile'))`
Then I have added this stage to the jenkins pipeline: 
``` 
        stage("Lint") {

            steps {
                script {
                    sh '''
                    pip3 install pre-commit
                    git ls-files -- models/mdh/acm/attributes/twh | xargs pre-commit run --files
                    '''
                }
            }
        }
``` 
what I expect is that Jenkins use this key to pass it to dbt so SQLFLUFF can do the linting. But what happens is that SQLFLUFF fails because dbt can't connect to the database (SQLFLUFF templater is set to `dbt`). 

### Expected Behaviour

SQLFLUFF to lint the code after dbt connects to the database during linting stage in the Jenkins CI pipeline 

### Observed Behaviour

I face this error `Error: 'NoneType' object has no attribute 'keys'` after running the Jenkins pipeline: 
``` 
dbt tried to connect to the database and failed: you could use 'execute' to skip the database calls. Seehttps://docs.getdbt.com/reference/dbt-jinja-functions/execute/
Error: 'NoneType' object has no attribute 'keys'
This occurs most often during incorrect sorting of ephemeral models before linting. Please report this error on github at https://github.com/sqlfluff/sqlfluff/issues, including both the raw and compiled sql for the model affected. 
``` 

### How to reproduce

In my local, I run `git ls-files -- models/mdh/acm/attributes/twh | xargs pre-commit run --files` and it lints very well. For remote, What I do is to push the code to the remote repo and run the Jenkins CI pipeline. 

### Dialect

bigquery

### Version

SQLFLUFF == 2.2.0
dbt-bigquery==1.5.1
sqlfluff-templater-dbt==2.2.0

### Configuration

my `.sqlfluff` looks like this:
``` 
[sqlfluff]
verbose = 1
templater = dbt
dialect = bigquery
sql_file_exts = .sql
max_line_length = 120
rules = CP01

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff.templater.dbt]
project_dir = "./"
profiles_dir = "./"
target = "nonprod"
``` 

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
