### ISSUE TITLE
Character count does not calculate correctly when using a Jinja placeholder in the template

### ISSUE THREAD

**Issue by ishiis** [sqlfluff/sqlfluff#5393]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When I execute the `sqlfluff lint` command on SQL with a Jinja placeholder in the template, I encounter a bug.

I have set the `max_line_length` to 80. The actual SQL line length is 61 characters.
However, the command results in a line length of 91 characters.

The character count does not calculate correctly when using a Jinja placeholder in the template.

```bash
% cat example.sql
SELECT * FROM `{{ var.value.gcp_project_id }}.dataset.table`;

% head -1 example.sql | tr -d '\n' | wc -c
61

% sqlfluff lint example.sql
== [example.sql] FAIL
L: 1 | P: 1 | LT05 | Line is too long (91 > 80).
| [layout.long_lines]
All Finished 📜 🎉!
```

### Expected Behaviour

The expected behavior is not to fail if the number of characters in the line is less than `max_line_length`.

### Observed Behaviour

The observed behavior is that it fails even if the number of characters on the line is less than `max_line_length`.

### How to reproduce

Here are the steps to reproduce this issue:

```bash
% echo 'SELECT * FROM `{{ var.value.gcp_project_id }}.dataset.table`;' > example.sql
% sqlfluff lint example.sql
```

### Dialect

bigquery

### Version

```bash
% sqlfluff --version
sqlfluff, version 2.3.5
```

vscode-sqlfluff version is `2.4.4`.

### Configuration

```toml
[tool.sqlfluff.core]
dialect = "bigquery"
templater = "jinja"
sql_file_exts = ".sql,.sql.j2,.dml,.ddl"
max_line_length = 80

[tool.sqlfluff.indentation]
indented_joins = false
indented_using_on = true
template_blocks_indent = false

[tool.sqlfluff.templater]
unwrap_wrapped_queries = true

[tool.sqlfluff.templater.jinja.context]
var.value = "" # for apache airflow variables

[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "upper"
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
