### ISSUE TITLE
Hope to support diff-quality in pre-commit hooks.

### ISSUE THREAD

**Issue by maoxingda** [sqlfluff/sqlfluff#5451]
### Search before asking

- [x] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

**The following command runs successfully from the command line, but when placed in a pre-commit hook, it does not detect violations**

```
conda run -n env-name diff-quality --violations sqlfluff --compare-branch origin/main
```

```yaml
repos:
  - repo: local
    hooks:
      - id: sqlfluff
        name: sqlfluff
        entry: conda run -n env-name diff-quality --violations sqlfluff --compare-branch origin/main
        language: system
        types: [sql]
```

### Dialect

no

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
