### ISSUE TITLE
Greenplum: set_expression in create_table_as

### ISSUE THREAD

**Issue by kkozhakin** [sqlfluff/sqlfluff#5550]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

`Set_expression` in `create_table_as` does not correctly work with `distributed_by` if last clause is not `from_clause` without brackets:
Correctly:
```sql
create table test_with_union as (
select distinct f1, f2
from table_1
union all
select unnest(array['1', '2']), unnest(array['_total_', '_total_'])
)
distributed randomly;
```
Correctly:
```sql
create table test_with_union as
select distinct f1, f2
from table_1
union all
select unnest(array['1', '2']), unnest(array['_total_', '_total_']) from table_2
distributed randomly;
```
Correctly:
```sql
create table test_with_union as
select distinct f1, f2
from table_1
union all
select unnest(array['1', '2']), unnest(array['_total_', '_total_'])
;
```
Incorrectly:
```sql
create table test_with_union as
select distinct f1, f2
from table_1
union all
select unnest(array['1', '2']), unnest(array['_total_', '_total_'])
distributed randomly;
```
I tried to fix it in the code, but it didn't work.

### Expected Behaviour

```yml
file:
- statement:
    create_table_as_statement:
    - keyword: create
    - keyword: table
    - table_reference:
        naked_identifier: test_with_union
    - keyword: as
      set_expression:
      - select_statement:
          select_clause:
          - keyword: select
          - select_clause_modifier:
              keyword: distinct
          - select_clause_element:
              column_reference:
                naked_identifier: f1
          - comma: ','
          - select_clause_element:
              column_reference:
                naked_identifier: f2
          from_clause:
            keyword: from
            from_expression:
              from_expression_element:
                table_expression:
                  table_reference:
                    naked_identifier: table_1
      - set_operator:
        - keyword: union
        - keyword: all
      - select_statement:
          select_clause:
          - keyword: select
          - select_clause_element:
              function:
                function_name:
                  function_name_identifier: unnest
                bracketed:
                  start_bracket: (
                  expression:
                    typed_array_literal:
                      array_type:
                        keyword: array
                      array_literal:
                      - start_square_bracket: '['
                      - quoted_literal: "'1'"
                      - comma: ','
                      - quoted_literal: "'2'"
                      - end_square_bracket: ']'
                  end_bracket: )
          - comma: ','
          - select_clause_element:
              function:
                function_name:
                  function_name_identifier: unnest
                bracketed:
                  start_bracket: (
                  expression:
                    typed_array_literal:
                      array_type:
                        keyword: array
                      array_literal:
                      - start_square_bracket: '['
                      - quoted_literal: "'_total_'"
                      - comma: ','
                      - quoted_literal: "'_total_'"
                      - end_square_bracket: ']'
                  end_bracket: )
    - distributed_by:
      - keyword: distributed
      - keyword: randomly
- statement_terminator: ;
```

### Observed Behaviour

SQLParseError: Could not parse

### How to reproduce

```sql
create table test_with_union as
select distinct f1, f2
from table_1
union all
select unnest(array['1', '2']), unnest(array['_total_', '_total_'])
distributed randomly;
```

### Dialect

greenplum

### Version

sqlfluff-3.0.0a4

### Configuration

Test in repo

### Are you willing to work on and submit a PR to address the issue?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
