### ISSUE TITLE
SQLFluff gets different results in Github Actions to locally

### ISSUE THREAD

**Issue by mwstanleyft** [sqlfluff/sqlfluff#5551]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Using the dbt templater, my file passes in the local environment but has a linting error with LT02 when run in a Github Action

### Expected Behaviour

The behaviour should be consistent between local and Github Actions

### Observed Behaviour

Locally I get no linting errors. In GitHub actions I get a linting error from LT02.

### How to reproduce

Here is the minimal .sql file that I have been able to reproduce the problem with:

```
{{ config(
    materialized='incremental'
) }}

WITH
test AS (
    SELECT 1
    FROM `test`
    WHERE
        TRUE
        {% if is_incremental() %}
            AND TRUE
        {% endif %}
    GROUP BY 1
)

SELECT * FROM test
```

And here is my github action code:

```
name: SQLFluff

on:
  pull_request:
    paths:
      - '**.sql'

permissions:
  contents: 'read'
  pull-requests: 'read'
  id-token: 'write'

jobs:
  lint-models:
    name: "Lint dbt models"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.9']
        gcp-project: ['***REDACTED***']
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          project_id: ${{ matrix.gcp-project }}
          workload_identity_provider: '***REDACTED***'
          service_account: '***REDACTED***@***REDACTED***.gserviceaccount.com'
      - name: 'Set up gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Install Python'
        uses: 'actions/setup-python@v4'
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Python Dependencies"
        run: 'pip install dbt-core==1.6.9 dbt-bigquery==1.6.9 sqlfluff==2.3.5 sqlfluff-templater-dbt==2.3.5'
      - name: 'Install dbt dependencies'
        run: 'dbt deps --project-dir ***REDACTED***'      
      - name: Get all changed model SQL files
        id: changed-files-models
        uses: tj-actions/changed-files@v37
        with:
          files: ***REDACTED***/**/*.sql
      - name: Lint dbt models
        if: steps.changed-files-models.outputs.any_changed == 'true'
        shell: bash -l {0}
        run: |
          sqlfluff lint --format github-annotation-native --annotation-level failure ${{ steps.changed-files-models.outputs.all_changed_files }}
```

Locally this results in no linting problems, whereas in Github Actions LT02 raises an error on line 11 `LT02: Expected indent of 4 spaces. [layout.indent]` (that's the line with `{% if is_incremental() %}`.

Local output:
```
╰─# sqlfluff lint test.sql --config /workspaces/***REDACTED***/.sqlfluff                                                                                                            
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
All Finished 📜 🎉!    
```

### Dialect

bigquery

### Version

╰─# sqlfluff --version                                                                      
sqlfluff, version 2.3.5
╰─# python --version                                         
Python 3.9.17

dbt templater 2.3.5 as well, and dbt-core and dbt-bigquery v1.6.9

### Configuration

```
[sqlfluff]
dialect = bigquery
templater = dbt
max_line_length = 0
exclude_rules = ST06
large_file_skip_byte_limit = 75000

[sqlfluff:templater:dbt]
project_dir = ***
profiles_dir = ***
profile = ***
target = ***
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
