### ISSUE TITLE
dbt support for a dbt proj in a subfolder of a git repo

### ISSUE THREAD

**Issue by lei0zhou** [sqlfluff/sqlfluff#5833]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

the dbt project is in a subfolder of a git repo, pre-commit was setup in the root folder, with the following,

```
      - id: sqlfluff-lint
        verbose: true
        additional_dependencies:
          ["dbt-snowflake", "dbt-duckdb", "sqlfluff-templater-dbt"]
        files: "analytics/models"
```
running 
```
pre-commit run sqlfluff-lint --all-files
```
I got 
```WARNING    Attempt to set templater to dbt failed. Using jinja templater. Templater cannot be set in a .sqlfluff file in a subdirectory of the current working directory. It can be set in a .sqlfluff in the current working directory. See Nesting section of the docs for more details. 
```

Is there a way  to use dbt as the tempater?

### Dialect

not particular

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
