### ISSUE TITLE
Automate pypi release on gh tag?

### ISSUE THREAD

**Issue by nolanbconaway** [sqlfluff/sqlfluff#604]
Per maintainer meetup, here is a [workflow](https://github.com/nolanbconaway/shabadoo/blob/7fbc5bdfea5ff3e0d0357d788d5c3b09a1168dc7/.github/workflows/push_release_to_pypi.yml) i use to push a new releases to pypi whenever a GH tag is created. I'm never sure if i got the `on:` section just right but it seems to work for me!

```yaml
name: Release PyPi Version

on:
  release:
    types:
      - published

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install twine wheel --upgrade

      - name: Build Distribution
        run: python setup.py sdist bdist_wheel

      - name: Publish Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
```
