### ISSUE TITLE
Rule references.qualification flags single-table subquery

### ISSUE THREAD

**Issue by linusjf** [sqlfluff/sqlfluff#6557]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

`googlesoln.sql`

WITH                                                         mutual_friends AS (
    SELECT friend_id
    FROM
      friends
    WHERE                                                        user_id = (                                                  SELECT user_id
        FROM                                                         users
        WHERE
          user_name = 'Karl'                                     )
    INTERSECT
    SELECT friend_id
    FROM                                                         friends                                                  WHERE                                                        user_id = (
        SELECT user_id                                             FROM                                                         users                                                    WHERE                                                        user_name = 'Hans'                                     )                                                      )
SELECT
  user_id,
  user_name                                                FROM                                                         users                                                    WHERE                                                        user_id IN (SELECT friend_id                                           FROM
      mutual_friends                                         );

The above SQL is flagged by the rule references.qualification for the subqueries that use only a single table.

### Expected Behaviour

The inner single-table subqueries must be ignored by this rule.

### Observed Behaviour

Output:

== [googlesoln.sql] FAIL                                   L:   8 | P:  16 | RF02 | Unqualified reference 'user_id' found in select with                                                                | more than one referenced table/view.                                                                                | [references.qualification]        L:  12 | P:  11 | RF02 | Unqualified reference 'user_name' found in select with                                                              | more than one referenced table/view.                                                                                | [references.qualification]        L:  20 | P:  16 | RF02 | Unqualified reference 'user_id' found in select with                                                                | more than one referenced table/view.
                       | [references.qualification]        L:  24 | P:  11 | RF02 | Unqualified reference 'user_name' found in select with                                                              | more than one referenced table/view.                                                                                | [references.qualification]        L:  34 | P:  12 | RF02 | Unqualified reference 'friend_id' found in select with                                                              | more than one referenced table/view.                                                                                | [references.qualification]

### How to reproduce

sqlfluff lint --dialect sqlite -- googlesoln.sql 

### Dialect

sqlite

### Version

sqlfluff, version 3.3.0

### Configuration

.sqlfluff

```toml
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.identifiers]
extended_capitalisation_policy = lower

[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = upper

[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = upper

# The default configuration for the not equal convention rule is "consistent"
# which will auto-detect the setting from the rest of the file. This
# is less desirable in a new project and you may find this (slightly
# more strict) setting more useful.

[sqlfluff:rules:convention.not_equal] 
# Default to preferring the "c_style" (i.e. `!=`)          
preferred_not_equal_style = c_style                                                                                   

[sqlfluff:rules:layout.select_targets]                     
wildcard_policy = multiple
```                                                                                            

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
