### ISSUE TITLE
Lack of Support for Variable Substitution Results in Parsing Errors for `TARGET_LAG`

### ISSUE THREAD

**Issue by LoganPrice344** [sqlfluff/sqlfluff#6563]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Linter threw an error when encountering valid code.

### Expected Behaviour

The check should pass.

### Observed Behaviour

The following exception is surfaced.
```
== [test.sql] FAIL
L: 104 | P:   1 |  PRS | Line 104, Position 1: Found unparsable section: 'CREATE
                       | OR ALTER VIEW ${view_with_column_...'
```
This seems to be the result of the way that the parser handles template variables, by dropping the `${}` parsing the name of the variable inside. This does not work for the `TARGET_LAG` variable regex due to the expectation of a specification of time. This is the result of [this](https://github.com/sqlfluff/sqlfluff/pull/6201/files) PR.

### How to reproduce

The following code causes the problem:
```
CREATE OR REPLACE DYNAMIC TABLE DT_WITH_MULTIPLE_DAYS_LAG
TARGET_LAG = '${my_time_variable}'
WAREHOUSE = mywh
AS
SELECT * FROM my_table;
```

### Dialect

Snowflake

### Version

V3.3.0

### Configuration

```toml
[tool.sqlfluff.core]
exclude_rules = ["layout.long_lines", "references.special_chars"]
dialect = "snowflake"
fix_even_unparsable = true
large_file_skip_byte_limit = 0
processes = 0
templater = "placeholder"

[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "upper"

[tool.sqlfluff.templater.placeholder]
param_style = "flyway_var"

"flyway:database" = "database"
"flyway:defaultSchema" = "defaultSchema"
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
