### ISSUE TITLE
Linter does not flag invalid string concatenations

### ISSUE THREAD

**Issue by TheCleric** [sqlfluff/sqlfluff#6616]
### Search before asking

- [x] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When doing a string concatenation via a `+` sign in dialects that do not support it (such as spark and databricks), sqlfluff fails to flag this as invalid SQL.

### Expected Behaviour

sqlfluff will flag invalid string concatenations, and potentially guide the user to use the correct operator instead (such as `||` in databricks) or fix if desired.

I know this would be difficult to impossible for complex uses cases, but I feel like this should at least occur for simple use cases (i.e., a string constant `+` something else).

### Observed Behaviour

sqlfluff produces no warnings or errors on invalid string concatenations using a `+` on dialects that do not support it.

### How to reproduce

The following minimal reproducible case produces no errors in sqlfluff for the databricks dialect:

```sql
SELECT 'a' + 'b'
```

Whereas actually executing it in a Databricks console returns the following error:

```
[DATATYPE_MISMATCH.BINARY_OP_WRONG_TYPE] Cannot resolve "(a + b)" due to data type mismatch: the binary operator requires the input type ("NUMERIC" or "INTERVAL DAY TO SECOND" or "INTERVAL YEAR TO MONTH" or "INTERVAL"), not "STRING". SQLSTATE: 42K09; line 1, pos 7
```

### Dialect

databricks

### Version

sqlfluff, version 3.3.0
Python 3.10.13

### Configuration

```toml
[sqlfluff]
verbose = 1
dialect = databricks
max_line_length = 120
exclude_rules = CP02, ST06
warnings = RF03
large_file_skip_byte_limit = 0

[sqlfluff:indentation]
tab_space_size = 2
indented_joins = True
indented_ctes = True
indented_using_on = True
indented_on_contents = True
# indented_then = True
# indented_then_contents = True
allow_implicit_indents = True
template_blocks_indent = True

[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = upper

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = upper
```

### Are you willing to work on and submit a PR to address the issue?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
