### ISSUE TITLE
Cast is not null operator

### ISSUE THREAD

**Issue by kkozhakin** [sqlfluff/sqlfluff#6961]
### Search before asking

- [x] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Failed cast `is not null` operator

Maybe, need to add operator for is_not_null:

```
old:
    - keyword: IS
    - keyword: NOT
    - null_literal: 'NULL'
new:
    - is_not_null_operator: 'IS NOT NULL'
```

### Expected Behaviour

 ```yaml
    - select_statement:
        select_clause:
          keyword: select
          select_clause_element:
            expression:
              cast_expression:
                expression:
                - column_reference:
                    naked_identifier: f
                - is_not_null_operator: 'IS NOT NULL'
                casting_operator: '::'
                data_type:
                  keyword: INT
            alias_expression:
              keyword: AS
              naked_identifier: dmg_flg
```

### Observed Behaviour

`Found unparsable section: '::INT AS dmg_flg'`

### How to reproduce

`SELECT  'w' IS NOT NULL::INT AS dmg_flg`

### Dialect

posgres

### Version

3.4.1

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
