### ISSUE TITLE
Upgrade OverlapsClauseSegment

### ISSUE THREAD

**Issue by kkozhakin** [sqlfluff/sqlfluff#6963]
### Search before asking

- [x] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

OverlapsClauseSegment not supported FunctionContentsExpressionGrammar

### Expected Behaviour

```yaml
- statement:
    select_statement:
      select_clause:
      - keyword: SELECT
      - select_clause_element:
          column_reference:
            naked_identifier: start_date_1
      - comma: ','
      - select_clause_element:
          column_reference:
            naked_identifier: start_date_2
      - comma: ','
      - select_clause_element:
          column_reference:
            naked_identifier: end_date
      from_clause:
        keyword: FROM
        from_expression:
          from_expression_element:
            table_expression:
              table_reference:
                naked_identifier: test_overlaps
      where_clause:
        keyword: WHERE
        expression:
          overlaps_clause:
          - bracketed:
            - start_bracket: (
            - datetime_literal:
                datetime_type_identifier:
                  keyword: DATE
                quoted_literal: "'2023-12-30'"
            - comma: ','
            - datetime_literal:
                datetime_type_identifier:
                  keyword: DATE
                quoted_literal: "'2024-01-14'"
            - end_bracket: )
          - keyword: OVERLAPS
          - bracketed:
              start_bracket: (
              expression:
                function:
                  function_name:
                    function_name_identifier: GREATEST
                  function_contents:
                    bracketed:
                    - start_bracket: (
                    - expression:
                        column_reference:
                          naked_identifier: start_date_1
                    - comma: ','
                    - expression:
                        column_reference:
                          naked_identifier: start_date_2
                    - end_bracket: )
              comma: ','
              column_reference:
                naked_identifier: end_date
              end_bracket: )
- statement_terminator: ;
```

### Observed Behaviour

`Found unparsable section: 'overlaps (greatest(  ...'`

### How to reproduce

```
SELECT
    start_date_1,
    start_date_2,
    end_date
FROM test_overlaps
WHERE (DATE '2023-12-30', DATE '2024-01-14') OVERLAPS (GREATEST(start_date_1, start_date_2), end_date);
```

### Dialect

postgres

### Version

3.4.1

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
